name: Build and Push to DockerHUB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Extract Exim Version from Dockerfile
      - name: Extract Exim Version
        id: exim_version
        run: |
          EXIM_VERSION=$(grep "^ARG EXIM_VERSION" Dockerfile | cut -d '=' -f2)
          echo "EXIM_VERSION=$EXIM_VERSION" >> $GITHUB_ENV

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build and push Docker image with both tags
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            olegeech/exim-alpine:latest
            olegeech/exim-alpine:${{ env.EXIM_VERSION }}

      # Step 6: Verify the image
      - name: Image digest verification
        run: docker run --rm olegeech/exim-alpine:${{ env.EXIM_VERSION }} -bV
